import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  page.setDefaultTimeout(5000);
  await page.goto('http://bc-techdays24-demo-vm.westeurope.cloudapp.azure.com:5141/');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByPlaceholder('name@example.com').click();
  let email = "user" + Math.floor(Math.random() * 100000) + "@example.com";
  await page.getByPlaceholder('name@example.com').fill(email);
  await page.getByPlaceholder('name@example.com').press('Tab');
  await page.locator('input[name="Input\\.Password"]').fill('Super5ecret!');
  await page.locator('input[name="Input\\.Password"]').press('Tab');
  await page.locator('input[name="Input\\.ConfirmPassword"]').fill('Super5ecret!');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('link', { name: 'Click here to confirm your' }).click();
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByPlaceholder('name@example.com').click();
  await page.getByPlaceholder('name@example.com').fill(email);
  await page.getByPlaceholder('name@example.com').press('Tab');
  await page.getByPlaceholder('password').fill('Super5ecret!');
  await page.getByRole('button', { name: 'Log in' }).click();
  await expect(page.locator('div').filter({ hasText: `${email} Sign out` }).nth(1)).toBeVisible();
  await expect(page.getByRole('link', { name: 'Log in' })).not.toBeVisible();
  await expect(page.locator('div').filter({ hasText: `${email} Sign out` }).nth(1)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Register' })).not.toBeVisible();
  await page.waitForTimeout(2000);
  await page.getByText('The Baconatorizor It has').click();
  await page.getByRole('slider').fill('14');
  await page.getByRole('combobox').selectOption('9');
  await page.getByRole('combobox').selectOption('15');
  await page.getByRole('button', { name: 'Order >' }).click();
  await page.getByText('Buffalo chicken Spicy chicken').click();
  await page.getByRole('slider').fill('11');
  await page.getByRole('combobox').selectOption('18');
  await page.getByRole('button', { name: 'Order >' }).click();
  await page.getByRole('link', { name: 'Order >' }).click();
  await page.locator('.is-valid').first().click();
  await page.locator('.is-valid').first().fill('Tobias Fenster');
  await page.locator('.is-valid').first().press('Tab');
  await page.getByLabel('Line1').fill('Kinepolis');
  await page.getByLabel('Line1').press('Tab');
  await page.locator('div:nth-child(4) > div > .is-valid').press('Tab');
  await page.locator('div:nth-child(5) > div > .is-valid').fill('Antwerp');
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.locator('.is-invalid').first().click();
  await page.locator('.is-invalid').first().fill('Belgium');
  await page.locator('.is-invalid').first().press('Tab');
  await page.locator('.is-invalid').fill('12345');
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.getByRole('button', { name: 'Place order' }).click();
  await page.getByRole('link', { name: 'Get Pizza' }).click();
  await page.getByRole('link', { name: 'My Orders' }).click();
  await page.waitForTimeout(4000);
  await page.getByRole('link', { name: 'Track >' }).click();
  await expect(page.getByText('" The Baconatorizor ')).toBeVisible();
  await expect(page.getByText('+ Onions')).toBeVisible();
  await expect(page.getByText('+ Duck sausage')).toBeVisible();
  await expect(page.getByText('" Buffalo chicken ')).toBeVisible();
  await expect(page.getByText('+ Steak')).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
});